name: .NET Core Build and Push

on:
  push:
    branches:
      - dev
      - trunk
    paths-ignore: 
      - README.md
      - terraform/**
      - .devcontainer/**
      - .gitignore
      - .github/**
  workflow_dispatch:
    
jobs:
  artifact:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build -c release --no-restore
    - name: Publish
      run: dotnet publish -o app
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.0.0
      with:
        name: loco-logo
        path: app/
  container:
    needs: artifact
    if: github.ref == 'refs/heads/trunk'
    runs-on: ubuntu-latest
    steps:    
    - uses: actions/checkout@v2
    - name: Download a Build Artifact
      uses: actions/download-artifact@v3.0.0
      with:
        name: loco-logo
        path: app
    - name: Docker Build
      shell: bash
      run: |
        DOCKER_BUILDKIT=1 docker build . -t ghcr.io/${GITHUB_REPOSITORY,,}:$(date +%Y%m%d.$GITHUB_RUN_NUMBER)
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Docker Publish
      shell: bash
      run: |
        docker push ghcr.io/${GITHUB_REPOSITORY,,}:$(date +%Y%m%d.$GITHUB_RUN_NUMBER)
